baseURL = "https://prakritibista.com.np/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Prakriti Bista"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 4
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = "Basundhara, Kathmandu , Nepal"
author = "Prakriti Bista"
copyright = "Copyright &copy; 2020 Prakriti Bista"
description = "This is meta description"
email = "bista.prakriti1999@gmail.com"
google_analytics_id = ""
home = "Home"
logo = "images/logo.png"
phone = "+977 9860485617"
theme_color = "#1C1C1C"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = ""
icon = "ti-facebook"
[[params.social]]
URL = "https://www.instagram.com/bista.prakriti1999"
icon = "ti-instagram"
[[params.social]]
URL = "https://github.com/Praks-Bista"
icon = "ti-github"
[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
